---
name: Feature request [Unsctructured]
about: Unsctructured feate template
title: "<title>"
---

### Brief summary *
<!-- text -->


### User story *
<!-- text -->


### Context / Problem *
<!-- text -->


### In scope *
<!-- text in list -->
- 

### Out of scope
<!-- text in list -->
- 

### Proposed approach / Implementation notes

<!-- text in list -->
- 

### UX/UI links
<!-- text -->
- 

### Dependencies
<!-- text -->
- 

### Risks & constraints
<!-- text -->
- 

### Acceptance criteria *
<!-- text -->
- 

### Definition of Done *

- [ ] UX/UI review approved
- [ ] Code review approved (≥1 approver)
- [ ] Documentation updated (README / ADR / API)
- [ ] Release notes prepared
- [ ] Successfully tested in Staging
- [ ] Rollout plan defined (and rollback plan if needed)

### Test plan
<!-- text -->
- 

### Success metrics / Impact
<!-- text -->
- 

### Rollout / Release plan
<!-- text -->
- 

### Links & related issues
<!-- text -->
- 

### Additional notes
<!-- text -->
